import type {
  TradeBrokerProfile,
  TradeCostProfile,
  TradeCryptoMarketType,
  TradeExecutionType,
  TradeFundingDirection,
  TradeInstrumentType,
} from '@/lib/types/trade'
import { normalizeTradeBrokerProfile } from '@/lib/utils/trade-preset-normalizers'

export type TradeBrokerProfilePreset = {
  value: TradeBrokerProfile
  label: string
  description: string
  defaultInstrumentType: TradeInstrumentType | null
  defaultCostProfile: TradeCostProfile
  defaultFees: number | null
  defaultExchangeFees: number | null
  defaultFundingFees: number | null
  defaultSpreadCost: number | null
  defaultSlippage: number | null
  defaultCurrency: string | null
  defaultPointValue: number | null
  defaultCryptoMarketType: TradeCryptoMarketType
  defaultExecutionType: TradeExecutionType
  defaultFundingDirection: TradeFundingDirection
  defaultFundingRateBps: number | null
  defaultFundingIntervals: number | null
  defaultMakerFeeBps: number | null
  defaultTakerFeeBps: number | null
  defaultQuoteAsset: string | null
  defaultLeverage: number | null
}

const brokerProfiles: Record<TradeBrokerProfile, TradeBrokerProfilePreset> = {
  manual: {
    value: 'manual',
    label: 'Kein Broker-Profil',
    description: 'Alles frei steuern. Gut für Imports, Backfills oder ungewöhnliche Setups.',
    defaultInstrumentType: null,
    defaultCostProfile: 'manual',
    defaultFees: null,
    defaultExchangeFees: null,
    defaultFundingFees: null,
    defaultSpreadCost: null,
    defaultSlippage: null,
    defaultCurrency: null,
    defaultPointValue: null,
    defaultCryptoMarketType: 'manual',
    defaultExecutionType: 'manual',
    defaultFundingDirection: 'manual',
    defaultFundingRateBps: null,
    defaultFundingIntervals: null,
    defaultMakerFeeBps: null,
    defaultTakerFeeBps: null,
    defaultQuoteAsset: null,
    defaultLeverage: null,
  },
  'ibkr-pro': {
    value: 'ibkr-pro',
    label: 'Interactive Brokers Pro',
    description: 'Aktien-/ETF-Profil mit separater Kommission, kleineren Börsengebühren und sauberem Spread-Block.',
    defaultInstrumentType: 'stocks',
    defaultCostProfile: 'stocks-light',
    defaultFees: 0.75,
    defaultExchangeFees: 0.35,
    defaultFundingFees: 0,
    defaultSpreadCost: 0.15,
    defaultSlippage: 0.15,
    defaultCurrency: 'USD',
    defaultPointValue: null,
    defaultCryptoMarketType: 'manual',
    defaultExecutionType: 'manual',
    defaultFundingDirection: 'manual',
    defaultFundingRateBps: null,
    defaultFundingIntervals: null,
    defaultMakerFeeBps: null,
    defaultTakerFeeBps: null,
    defaultQuoteAsset: null,
    defaultLeverage: null,
  },
  'trade-republic': {
    value: 'trade-republic',
    label: 'Trade Republic',
    description: 'Retail-Aktienprofil mit fixer Kommission, leichtem Spread-Klotz und kleiner Slippage.',
    defaultInstrumentType: 'stocks',
    defaultCostProfile: 'stocks-light',
    defaultFees: 1,
    defaultExchangeFees: 0,
    defaultFundingFees: 0,
    defaultSpreadCost: 0.3,
    defaultSlippage: 0.2,
    defaultCurrency: 'EUR',
    defaultPointValue: null,
    defaultCryptoMarketType: 'manual',
    defaultExecutionType: 'manual',
    defaultFundingDirection: 'manual',
    defaultFundingRateBps: null,
    defaultFundingIntervals: null,
    defaultMakerFeeBps: null,
    defaultTakerFeeBps: null,
    defaultQuoteAsset: null,
    defaultLeverage: null,
  },
  'tradovate-futures': {
    value: 'tradovate-futures',
    label: 'Tradovate Futures',
    description: 'Future-Profil mit separater Commission, Börsengebühr und engem Slippage-Fenster.',
    defaultInstrumentType: 'futures',
    defaultCostProfile: 'futures-standard',
    defaultFees: 3.2,
    defaultExchangeFees: 1.4,
    defaultFundingFees: 0,
    defaultSpreadCost: 0,
    defaultSlippage: 0.65,
    defaultCurrency: 'USD',
    defaultPointValue: 5,
    defaultCryptoMarketType: 'manual',
    defaultExecutionType: 'manual',
    defaultFundingDirection: 'manual',
    defaultFundingRateBps: null,
    defaultFundingIntervals: null,
    defaultMakerFeeBps: null,
    defaultTakerFeeBps: null,
    defaultQuoteAsset: null,
    defaultLeverage: null,
  },
  'ftmo-cfd': {
    value: 'ftmo-cfd',
    label: 'FTMO / Prop CFD',
    description: 'CFD-/Prop-Profil mit Spread-, Funding- und leichtem Execution-Block statt klarer Order-Kommission.',
    defaultInstrumentType: 'cfd',
    defaultCostProfile: 'cfd-standard',
    defaultFees: 0,
    defaultExchangeFees: 0,
    defaultFundingFees: 0.4,
    defaultSpreadCost: 1.3,
    defaultSlippage: 0.7,
    defaultCurrency: 'USD',
    defaultPointValue: 1,
    defaultCryptoMarketType: 'manual',
    defaultExecutionType: 'manual',
    defaultFundingDirection: 'manual',
    defaultFundingRateBps: null,
    defaultFundingIntervals: null,
    defaultMakerFeeBps: null,
    defaultTakerFeeBps: null,
    defaultQuoteAsset: null,
    defaultLeverage: null,
  },
  'binance-spot': {
    value: 'binance-spot',
    label: 'Binance Spot',
    description: 'Krypto-Spot-Profil mit Trading-Fee, kleinem Spread-Keil und deutlicherer Slippage.',
    defaultInstrumentType: 'crypto',
    defaultCostProfile: 'crypto-spot',
    defaultFees: null,
    defaultExchangeFees: 0,
    defaultFundingFees: 0,
    defaultSpreadCost: 0.6,
    defaultSlippage: 1.8,
    defaultCurrency: 'USDT',
    defaultPointValue: null,
    defaultCryptoMarketType: 'spot',
    defaultExecutionType: 'taker',
    defaultFundingDirection: 'flat',
    defaultFundingRateBps: 0,
    defaultFundingIntervals: 0,
    defaultMakerFeeBps: 10,
    defaultTakerFeeBps: 10,
    defaultQuoteAsset: 'USDT',
    defaultLeverage: 1,
  },
  'coinbase-spot': {
    value: 'coinbase-spot',
    label: 'Coinbase Spot',
    description: 'Krypto-Spot-Profil mit stärkerem Retail-Fee-Gewicht und ruhigerem Hebelkontext.',
    defaultInstrumentType: 'crypto',
    defaultCostProfile: 'crypto-spot',
    defaultFees: null,
    defaultExchangeFees: 0,
    defaultFundingFees: 0,
    defaultSpreadCost: 0.75,
    defaultSlippage: 1.3,
    defaultCurrency: 'USD',
    defaultPointValue: null,
    defaultCryptoMarketType: 'spot',
    defaultExecutionType: 'taker',
    defaultFundingDirection: 'flat',
    defaultFundingRateBps: 0,
    defaultFundingIntervals: 0,
    defaultMakerFeeBps: 40,
    defaultTakerFeeBps: 60,
    defaultQuoteAsset: 'USD',
    defaultLeverage: 1,
  },
  'bybit-spot': {
    value: 'bybit-spot',
    label: 'Bybit Spot',
    description: 'Krypto-Spot-Profil mit moderater Taker-Fee, leichtem Spread und USDT-Quote.',
    defaultInstrumentType: 'crypto',
    defaultCostProfile: 'crypto-spot',
    defaultFees: null,
    defaultExchangeFees: 0,
    defaultFundingFees: 0,
    defaultSpreadCost: 0.5,
    defaultSlippage: 1.1,
    defaultCurrency: 'USDT',
    defaultPointValue: null,
    defaultCryptoMarketType: 'spot',
    defaultExecutionType: 'taker',
    defaultFundingDirection: 'flat',
    defaultFundingRateBps: 0,
    defaultFundingIntervals: 0,
    defaultMakerFeeBps: 10,
    defaultTakerFeeBps: 10,
    defaultQuoteAsset: 'USDT',
    defaultLeverage: 1,
  },
  'mexc-spot': {
    value: 'mexc-spot',
    label: 'MEXC Spot',
    description: 'Krypto-Spot-Profil für MEXC mit leichten Trading-Fees, etwas Slippage und USDT-Quote.',
    defaultInstrumentType: 'crypto',
    defaultCostProfile: 'crypto-spot',
    defaultFees: null,
    defaultExchangeFees: 0,
    defaultFundingFees: 0,
    defaultSpreadCost: 0.65,
    defaultSlippage: 1.6,
    defaultCurrency: 'USDT',
    defaultPointValue: null,
    defaultCryptoMarketType: 'spot',
    defaultExecutionType: 'taker',
    defaultFundingDirection: 'flat',
    defaultFundingRateBps: 0,
    defaultFundingIntervals: 0,
    defaultMakerFeeBps: 0,
    defaultTakerFeeBps: 10,
    defaultQuoteAsset: 'USDT',
    defaultLeverage: 1,
  },
  'mexc-perps': {
    value: 'mexc-perps',
    label: 'MEXC Perps',
    description: 'Krypto-Perps-Profil für MEXC mit Funding-Komponente, taker-lastiger Fee und Perps-Kontext.',
    defaultInstrumentType: 'crypto',
    defaultCostProfile: 'crypto-perps',
    defaultFees: null,
    defaultExchangeFees: 0,
    defaultFundingFees: null,
    defaultSpreadCost: 0.55,
    defaultSlippage: 1.5,
    defaultCurrency: 'USDT',
    defaultPointValue: 1,
    defaultCryptoMarketType: 'perps',
    defaultExecutionType: 'taker',
    defaultFundingDirection: 'paid',
    defaultFundingRateBps: 1.6,
    defaultFundingIntervals: 1,
    defaultMakerFeeBps: 1,
    defaultTakerFeeBps: 4,
    defaultQuoteAsset: 'USDT',
    defaultLeverage: 6,
  },
  'bybit-perps': {
    value: 'bybit-perps',
    label: 'Bybit Perps',
    description: 'Perpetual-Krypto-Profil mit Trading-Fee, Funding-Komponente, engem Spread und Auto-P&L-Logik.',
    defaultInstrumentType: 'crypto',
    defaultCostProfile: 'crypto-perps',
    defaultFees: null,
    defaultExchangeFees: 0,
    defaultFundingFees: null,
    defaultSpreadCost: 0.45,
    defaultSlippage: 1.4,
    defaultCurrency: 'USDT',
    defaultPointValue: 1,
    defaultCryptoMarketType: 'perps',
    defaultExecutionType: 'taker',
    defaultFundingDirection: 'paid',
    defaultFundingRateBps: 1.5,
    defaultFundingIntervals: 1,
    defaultMakerFeeBps: 2,
    defaultTakerFeeBps: 5.5,
    defaultQuoteAsset: 'USDT',
    defaultLeverage: 5,
  },
  'okx-perps': {
    value: 'okx-perps',
    label: 'OKX Perps',
    description: 'Krypto-Perps-Profil mit leicht günstigerer Maker-Seite und eigenem Funding-Template.',
    defaultInstrumentType: 'crypto',
    defaultCostProfile: 'crypto-perps',
    defaultFees: null,
    defaultExchangeFees: 0,
    defaultFundingFees: null,
    defaultSpreadCost: 0.3,
    defaultSlippage: 1.0,
    defaultCurrency: 'USDT',
    defaultPointValue: 1,
    defaultCryptoMarketType: 'perps',
    defaultExecutionType: 'maker',
    defaultFundingDirection: 'paid',
    defaultFundingRateBps: 1.2,
    defaultFundingIntervals: 1,
    defaultMakerFeeBps: 2,
    defaultTakerFeeBps: 5,
    defaultQuoteAsset: 'USDT',
    defaultLeverage: 4,
  },
}

export function getTradeBrokerProfilePreset(profile?: string | null): TradeBrokerProfilePreset {
  return brokerProfiles[normalizeTradeBrokerProfile(profile)]
}

export function getBrokerProfileLabel(profile?: string | null): string {
  return getTradeBrokerProfilePreset(profile).label
}

export const brokerProfileOptions: Array<{ value: TradeBrokerProfile; label: string }> = [
  { value: 'manual', label: 'Kein Broker-Profil' },
  { value: 'trade-republic', label: 'Trade Republic' },
  { value: 'ibkr-pro', label: 'Interactive Brokers Pro' },
  { value: 'tradovate-futures', label: 'Tradovate Futures' },
  { value: 'ftmo-cfd', label: 'FTMO / Prop CFD' },
  { value: 'binance-spot', label: 'Binance Spot' },
  { value: 'coinbase-spot', label: 'Coinbase Spot' },
  { value: 'bybit-spot', label: 'Bybit Spot' },
  { value: 'bybit-perps', label: 'Bybit Perps' },
  { value: 'mexc-spot', label: 'MEXC Spot' },
  { value: 'mexc-perps', label: 'MEXC Perps' },
  { value: 'okx-perps', label: 'OKX Perps' },
]
